# Generated by Django 6.0 on 2026-01-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_title', models.CharField(max_length=100)),
                ('Room_rent', models.CharField(max_length=100)),
                ('Room_images', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Room_details', models.TextField()),
                ('Room_status', models.BooleanField(default=True)),
            ],
        ),
    ]
