# Generated by Django 6.0 on 2026-01-06 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='Room_status',
            new_name='Room_available',
        ),
    ]
