# Generated by Django 6.0 on 2026-01-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_room_status_listings_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='Room_security',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listings',
            name='Room_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='chair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='fan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='mattres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='ro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listings',
            name='Room_rent',
            field=models.IntegerField(),
        ),
    ]
