# Generated by Django 6.0 on 2026-01-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listings_ac_listings_room_security_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Room_images2',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='Room_images3',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='Room_images4',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='Room_images5',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
