# Generated by Django 6.0 on 2026-01-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_room_images2_listings_room_images3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='Room_images',
            new_name='Room_images1',
        ),
    ]
