# Generated by Django 6.0 on 2026-01-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_roombooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='user',
        ),
    ]
